### ISSUE TITLE
Error with the api request: /api?id-type=all

### ISSUE THREAD

**Issue by flicksolutions** [ediarum/ediarum.WEB#1]
When trying to install the latest Version 1.9.6 of ediarum.WEB with your Step-by-Step-Guide I am encountering an Error after trying to reach the _workshop.web_-Application:
(trying to open /exist/apps/workshop.web/index.html)

```XML
<exception>
<path>/db/apps/workshop.web/modules/view.xql</path>
<message>
edwebcontroller:api-get-001 Error with the api request: /api?id-type=all [at line 133, column 9, source: /opt/exist-db_5.2.0/exist-db/data/expathrepo/edweb-1.9.6/content/edweb-controller.xql] In function: edwebcontroller:api-get(xs:string) [1016:23:/opt/exist-db_5.2.0/exist-db/data/expathrepo/edweb-1.9.6/content/edweb-controller.xql] edweb:view-expand-links(node(), function(*)?) [47:5:/opt/exist-db_5.2.0/exist-db/data/expathrepo/edweb-1.9.6/content/edweb.xql]
</message>
</exception>
```

Also after dragging and dropping the _.xar_-Package in the Package-Manager, ediarum.WEB is not shown under the _installed Packages_.

Thank you for your help!

Edit: When I install v.1.1. of Ediarum.WEB the error does not occur..!

**Comment by MartinFechner** [comment]
Thank you for your question.

Please use for the Step-by-Step-Guide only the material which is linked in the presentation itself:

https://www.ediarum.org/docs/ediarum-web-step-by-step/download/ediarum.web_v1.1.0.2020-06-25.16-56-32.xar

ediarum.WEB is not shown under the installed packages because it is an library and not an app. I think there is an checkbox one must click to see the libraries as well.

I hope I could help you.

**Comment by flicksolutions** [comment]
Thank you for your answer!

So, there is no guide, tutorial, proper documentation for the current version?

ediarum.WEB pops up as a library. Thank you for pointing out that checkbox to me. 👍

**Comment by MartinFechner** [comment]
The documentation for API and the APPCONF the current version is linked in the README:

- https://github.com/ediarum/ediarum.WEB/blob/master/APPCONF.md
- https://github.com/ediarum/ediarum.WEB/blob/master/API.md

Still the Step-by-step-Tutorial must be updated. But the workflow of the tutorial is still the same.

- The functions are documented in the code (e.g. https://github.com/ediarum/ediarum.WEB/blob/master/content/edweb.xql). And you can use the eXist functionality to access it in a comfortable way: In the dashboard of your eXist installation open documentation and press generate (after installing ediarum.WEB). Then the library function should be listed in the documentation.

I hope I could help you. If you like ediarum.WEB please send us your feedback.
