### ISSUE TITLE
Versions and app Templates

### ISSUE THREAD

**Issue by Kolophonium0** [ediarum/ediarum.WEB#2]
The documentation on how to setup a webapp with ediarum.Web does mention downloadable app templates, but the workshop module you offer does only work with Version 1.1. Do you have some guidance for upgrading or on how to write own templates working with Version > 1.9?

**Comment by MartinFechner** [comment]
You are right, the step-by-step tutorial uses a previous ediarum.web version. I haven't it tested with the current one, but I think it shouldn't be to hard to upgrade. Please can you give me more details where you get an error?

**Comment by Kolophonium0** [comment]
> You are right, the step-by-step tutorial uses a previous ediarum.web version. I haven't it tested with the current one, but I think it shouldn't be to hard to upgrade. Please can you give me more details where you get an error?

It seems like view.xql is throwing errors regarding the use of /api?id-type=all

**Comment by Kolophonium0** [comment]
I can retry it and give you exact errors etc later this weeks.

**Comment by MartinFechner** [comment]
If you get an error regarding the use of `/api?id-type=all`, please try to open `localhost:8080/exist/apps/your-app-name/api?id-type=all` directly in the browser. What error do you get?

This endpoint uses all other object endpoint, so maybe one of the other endpoints causes the error. Please try to open every object endpoint manually (e.g. `/api/my-object-name`) and test if all endpoints working fine.

**Comment by Kolophonium0** [comment]
> If you get an error regarding the use of `/api?id-type=all`, please try to open `localhost:8080/exist/apps/your-app-name/api?id-type=all` directly in the browser. What error do you get?
> 
> This endpoint uses all other object endpoint, so maybe one of the other endpoints causes the error. Please try to open every object endpoint manually (e.g. `/api/my-object-name`) and test if all endpoints working fine.

Now i got the time to do this. I get following error. It seems to be connected to the new function app parameter introduced in V1.11:
![Screenshot_20211228_134727](https://user-images.githubusercontent.com/24278823/147567856-fb620d72-0e3d-4462-b14a-3c6b71ae1067.png)

**Comment by MartinFechner** [comment]
In the error message it seems to be the $cache parameter missing. Try to add it explicitly like this and to rebuild the cache: `/api/my-object-name?cache=reset`

Does you get this error on all object endpoints?

**Comment by Kolophonium0** [comment]
The endpoints seems to work all. It was the cache as u suggested. I fixed it by adding:
`let $cache := if (not(request:get-attribute("cache"))) then request:set-attribute("cache", "false") else ()`
to the workshop.webs view.xql.

**Comment by Kolophonium0** [comment]
> The endpoints seems to work all. It was the cache as u suggested. I fixed it by adding: `let $cache := if (not(request:get-attribute("cache"))) then request:set-attribute("cache", "false") else ()` to the workshop.webs view.xql.

Maybe the edweb.xql needs a catch for a non existing cache parameter?

**Comment by chpollin** [comment]
> The endpoints seems to work all. It was the cache as u suggested. I fixed it by adding: `let $cache := if (not(request:get-attribute("cache"))) then request:set-attribute("cache", "no") else ()` to the workshop.webs view.xql.

Thank you! You made my day! Had the same problem. This line fixed it. 

ediarum.WEB Version 1.13.4
eXist Version: 5.4.0
ediarum version: 4.0.2
